USE [prototype]
GO

/****** Object:  Table [dbo].[verb]    Script Date: 20/03/2019 14:08:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[verb](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[word] [varchar](255) NULL,
 CONSTRAINT [PK__verb__3213E83F4E0C286C] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[verb] ADD  CONSTRAINT [DF__verb__word__35BCFE0A]  DEFAULT (NULL) FOR [word]
GO

