USE [prototype]
GO

/****** Object:  Table [dbo].[noun]    Script Date: 20/03/2019 14:07:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[noun](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[word] [varchar](255) NULL,
 CONSTRAINT [PK__noun__3213E83FA06E27E8] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[noun] ADD  CONSTRAINT [DF__noun__word__2C3393D0]  DEFAULT (NULL) FOR [word]
GO

