USE [master]
GO

/****** Object:  Database [prototype]    Script Date: 20/03/2019 14:06:46 ******/
CREATE DATABASE [prototype]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prototype', FILENAME = N'C:\Users\Marten\prototype.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'prototype_log', FILENAME = N'C:\Users\Marten\prototype_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [prototype] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [prototype].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [prototype] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [prototype] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [prototype] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [prototype] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [prototype] SET ARITHABORT OFF 
GO

ALTER DATABASE [prototype] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [prototype] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [prototype] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [prototype] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [prototype] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [prototype] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [prototype] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [prototype] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [prototype] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [prototype] SET  DISABLE_BROKER 
GO

ALTER DATABASE [prototype] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [prototype] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [prototype] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [prototype] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [prototype] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [prototype] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [prototype] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [prototype] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [prototype] SET  MULTI_USER 
GO

ALTER DATABASE [prototype] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [prototype] SET DB_CHAINING OFF 
GO

ALTER DATABASE [prototype] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [prototype] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [prototype] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [prototype] SET QUERY_STORE = OFF
GO

USE [prototype]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [prototype] SET  READ_WRITE 
GO

